name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true      
        components: clippy, rustfmt  
        profile: default
    
    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test --verbose

    - name: Release
      run: cargo build --release
